#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nubia/cerro

PRODUCT_COPY_FILES += \
    vendor/nubia/cerro/proprietary/system/etc/pictureclassifier/MultiScenePictureClassifier.tflite:$(TARGET_COPY_OUT_SYSTEM)/etc/pictureclassifier/MultiScenePictureClassifier.tflite \
    vendor/nubia/cerro/proprietary/vendor/etc/acdbdata/pineapple_mtp/MTP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/pineapple_mtp/MTP_acdb_cal.acdb \
    vendor/nubia/cerro/proprietary/vendor/etc/acdbdata/pineapple_mtp/MTP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/pineapple_mtp/MTP_workspaceFileXml.qwsp \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/VNSConfig_4k.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/VNSConfig_4k.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/VNSQnnBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/VNSQnnBinary.bin \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/adaptive_config/mfnr_network_denoise_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/adaptive_config/mfnr_network_denoise_config.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/adaptive_shutter_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/adaptive_shutter_config.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/adaptive_shutter_config_moon.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/adaptive_shutter_config_moon.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/adaptive_shutter_config_night.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/adaptive_shutter_config_night.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/adaptive_shutter_config_renwen.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/adaptive_shutter_config_renwen.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/beautiful_app/preference_beautify0.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beautiful_app/preference_beautify0.json \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/beautiful_app/preference_beautify1.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beautiful_app/preference_beautify1.json \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/beautiful_app/preference_beautify2.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beautiful_app/preference_beautify2.json \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/debug/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/debug/camxoverridesettings.txt \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/dualcam_cali.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dualcam_cali.bin \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/eisoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/eisoverridesettings.txt \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/icon/water_mark_drawable_black.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_black.argb \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/icon/water_mark_drawable_black_eng.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_black_eng.argb \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/icon/water_mark_drawable_white.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_white.argb \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/icon/water_mark_drawable_white_eng.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_white_eng.argb \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/mfnr_network_denoise_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_network_denoise_config.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/mfnr_network_denoise_config_moon.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_network_denoise_config_moon.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/mfnr_network_denoise_config_night.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_network_denoise_config_night.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/mfnr_network_denoise_config_renwen.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_network_denoise_config_renwen.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/sr_x1_272_272_12Binary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_x1_272_272_12Binary.bin \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/sr_x2_272_272_12Binary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_x2_272_272_12Binary.bin \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/sr_x4_272_272_12Binary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_x4_272_272_12Binary.bin \
    vendor/nubia/cerro/proprietary/vendor/etc/camera/widelencalc_cali.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/widelencalc_cali.bin \
    vendor/nubia/cerro/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/nubia/cerro/proprietary/vendor/etc/init/android.hardware.secure_element.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element.rc \
    vendor/nubia/cerro/proprietary/vendor/etc/libnfc-hal-st.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st.conf \
    vendor/nubia/cerro/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/nubia/cerro/proprietary/vendor/etc/media_profiles_pineapple.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_pineapple.xml \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/json.lst:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/json.lst \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/lanai_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_ak991x_0.json \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/lanai_aw96103_0_sar_register_a.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_aw96103_0_sar_register_a.json \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/lanai_aw96103_0_sar_register_b.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_aw96103_0_sar_register_b.json \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/lanai_aw96103_0_sar_register_c.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_aw96103_0_sar_register_c.json \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/lanai_aw9610x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_aw9610x_0.json \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/lanai_fcal_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_fcal_ak991x_0.json \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/lanai_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_lsm6dso_0.json \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/lanai_mtp_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_mtp_ak991x_0.json \
    vendor/nubia/cerro/proprietary/vendor/etc/sensors/config/lanai_stk3b6x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_stk3b6x_0.json \
    vendor/nubia/cerro/proprietary/vendor/etc/st54l_conf.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st54l_conf.txt \
    vendor/nubia/cerro/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/nubia/cerro/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/nubia/cerro/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/nubia/cerro/proprietary/vendor/firmware/aw882xx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_acf.bin \
    vendor/nubia/cerro/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/nubia/cerro/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/nubia/cerro/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/nubia/cerro/proprietary/vendor/firmware/gen70900_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_zap.mbn \
    vendor/nubia/cerro/proprietary/vendor/firmware/goodix_cfg_group_9916r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_cfg_group_9916r.bin \
    vendor/nubia/cerro/proprietary/vendor/firmware/goodix_firmware_9916r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_9916r.bin \
    vendor/nubia/cerro/proprietary/vendor/firmware/haptic_ram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_ram.bin \
    vendor/nubia/cerro/proprietary/vendor/firmware/ois_dw9781_cerro_ov64b40.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_dw9781_cerro_ov64b40.prog \
    vendor/nubia/cerro/proprietary/vendor/firmware/ois_dw9784_cerro_imx800.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_dw9784_cerro_imx800.prog \
    vendor/nubia/cerro/proprietary/vendor/firmware/ois_dw9784_cerro_imx906.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_dw9784_cerro_imx906.prog \
    vendor/nubia/cerro/proprietary/vendor/firmware/ois_dw9784_cerro_ov50e40.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_dw9784_cerro_ov50e40.prog \
    vendor/nubia/cerro/proprietary/vendor/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v.mbn \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_imx800_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_imx800_cerro.bin \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_imx906_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_imx906_cerro.bin \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_ov12d2q_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_ov12d2q_cerro.bin \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_ov50e40_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_ov50e40_cerro.bin \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_ov64b40_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_ov64b40_cerro.bin \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_imx800_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_imx800_cerro.bin \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_imx906_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_imx906_cerro.bin \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_ov12d2q_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_ov12d2q_cerro.bin \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_ov50e40_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_ov50e40_cerro.bin \
    vendor/nubia/cerro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_ov64b40_cerro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_ov64b40_cerro.bin

PRODUCT_PACKAGES += \
    com.qti.ois.ois_dw9781_cerro_ov64b40 \
    com.qti.ois.ois_dw9784_cerro_imx800 \
    com.qti.ois.ois_dw9784_cerro_imx906 \
    com.qti.ois.ois_dw9784_cerro_ov50e40 \
    com.zte.eeprom.imx800_cerro \
    com.zte.eeprom.imx906_cerro \
    com.zte.eeprom.ov12d2q_cerro \
    com.zte.eeprom.ov50e40_cerro \
    com.zte.eeprom.ov64b40_cerro \
    com.zte.sensor.imx800_cerro \
    com.zte.sensor.imx906_cerro \
    com.zte.sensor.ov12d2q_cerro \
    com.zte.sensor.ov50e40_cerro \
    com.zte.sensor.ov64b40_cerro \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.zte.node.aicud \
    com.zte.node.capturepostprocess \
    com.zte.node.capturereprocess \
    com.zte.node.capturescale \
    com.zte.node.mcxrealtimepostprocess \
    com.zte.node.rawsvq \
    com.zte.node.realtimepostprocess \
    com.zte.node.sat \
    com.zte.node.satpostprocess \
    libcamxevainterface \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8650 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.metadataserializer \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.supres \
    com.qti.feature2.swmf \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom.sm8650 \
    camera.qcom \
    com.qti.chi.offline \
    com.qti.chi.override \
    fingerprint.gf95xx.default \
    sensors.hal.tof \
    libQnnHtpV75CalculatorStub \
    libQnnJsonProfilingReader \
    libVNSInterface \
    libarcsoft_hp_detection \
    libarcsoft_picselfie \
    libarcsoft_qnnhtp \
    libarcsoft_scbokeh_image \
    libarcsoft_scbokeh_video \
    libarcsoft_superportrait \
    libcamerapostproc \
    libcamxarcskinbeautiful \
    libcamxdepthbokeharc \
    libcamxncsdatafactory \
    libcamxremovefringer \
    libcamxselfiebokeharc \
    libcamxskytone \
    libcamxsuperres \
    libcamxwidelencalc \
    libchifeature2 \
    libgf_hal \
    librmca \
    libsky_cls_320 \
    libsky_seg_320 \
    libsky_seg_toning_320 \
    libsr_x1_272_272_12 \
    libsr_x2_272_272_12 \
    libsr_x4_272_272_12 \
    libtflite_model_depurple_544_544 \
    libyuv_sr \
    sensors.qsh \
    NubiaCamera \
    android.hardware.secure_element.xml \
    android.hardware.secure_element-service-aidl
